import type { Product } from "./types";

/**
 * Seed catalog. Copy is written to the Beyond Lace voice defined in
 * docs/brand/03-audience-and-aesthetics.md: elevation and reinvention, never
 * texture-and-density spec-speak. Every product leads with the transformation,
 * then earns it with the engineering underneath.
 *
 * Replace with live backend data once the commerce decision lands.
 */

const LENGTHS = [
  { label: '12"', value: "12", priceDelta: 0 },
  { label: '14"', value: "14", priceDelta: 4000 },
  { label: '16"', value: "16", priceDelta: 8000 },
  { label: '18"', value: "18", priceDelta: 13000 },
  { label: '20"', value: "20", priceDelta: 19000 },
  { label: '22"', value: "22", priceDelta: 26000 },
  { label: '24"', value: "24", priceDelta: 34000 },
  { label: '26"', value: "26", priceDelta: 44000, available: false },
];

const SHADES = [
  { label: "Natural Black", value: "natural-black", swatch: "#12100F" },
  { label: "Espresso", value: "espresso", swatch: "#2E1F1A" },
  { label: "Brunette", value: "brunette", swatch: "#5A3A28" },
  { label: "Honey Blonde", value: "honey-blonde", swatch: "#B8834A", priceDelta: 9000 },
  { label: "Platinum", value: "platinum", swatch: "#DFD3BE", priceDelta: 15000 },
];

const DENSITIES = [
  { label: "150% — Everyday", value: "150" },
  { label: "180% — Editorial", value: "180", priceDelta: 6000 },
  { label: "200% — Full Glamour", value: "200", priceDelta: 12000 },
];

export const catalog: Product[] = [
  {
    id: "bl-luxe-001",
    slug: "the-reinvention-hd-swiss-full-lace",
    title: "The Reinvention",
    line: "luxe",
    avatar: "transformation",
    tagline: "The wig you stop explaining.",
    description:
      "Hand-tied across a full HD Swiss lace cap, with knots bleached individually and a hairline plucked to sit the way your own would. The point is not that it looks like good hair. The point is that nobody asks about it.",
    price: 89500,
    compareAtPrice: 104000,
    currency: "USD",
    texture: "body-wave",
    laceType: "hd-swiss-full",
    shade: "natural-black",
    density: "180%",
    origin: "Single-donor virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS },
      { name: "Shade", values: SHADES },
      { name: "Density", values: DENSITIES },
    ],
    images: [
      { src: "aurora", alt: "The Reinvention full lace unit, body wave, natural black" },
      { src: "velvet", alt: "Hairline detail showing bleached knots and plucked density" },
      { src: "plum", alt: "The Reinvention styled, three-quarter view" },
    ],
    specs: [
      { label: "Cap", value: "Full HD Swiss lace, hand-tied throughout" },
      { label: "Hairline", value: "Pre-plucked, graduated density" },
      { label: "Knots", value: "Individually bleached" },
      { label: "Hair", value: "Single-donor virgin Remy, cuticle aligned" },
      { label: "Batch guarantee", value: "Texture and tone matched across every production run" },
      { label: "Lifespan", value: "18–36 months with Beyond Care maintenance" },
    ],
    rating: 4.9,
    reviewCount: 412,
    badges: ["Signature", "Camera-ready"],
    inStock: true,
  },
  {
    id: "bl-luxe-002",
    slug: "the-occasion-13x6-hd-frontal",
    title: "The Occasion",
    line: "luxe",
    avatar: "transformation",
    tagline: "For the day the photographs outlive the day.",
    description:
      "Built for the moments that get framed. A 13x6 HD Swiss frontal that survives flash photography, close-up video, and the second look in daylight — the three conditions where ordinary lace gives itself away.",
    price: 76500,
    compareAtPrice: 84500,
    currency: "USD",
    texture: "straight",
    laceType: "hd-swiss-13x6",
    shade: "espresso",
    density: "180%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS },
      { name: "Shade", values: SHADES },
      { name: "Density", values: DENSITIES },
    ],
    images: [
      { src: "plum", alt: "The Occasion 13x6 frontal, straight, espresso" },
      { src: "velvet", alt: "Frontal parting space detail" },
    ],
    specs: [
      { label: "Cap", value: "13x6 HD Swiss frontal, machine-wefted back" },
      { label: "Parting", value: "6 inches deep — any part, any direction" },
      { label: "Knots", value: "Individually bleached" },
      { label: "Finish", value: "Melt-tested under flash and 4K video" },
      { label: "Lifespan", value: "12–24 months with Beyond Care maintenance" },
    ],
    rating: 4.8,
    reviewCount: 287,
    badges: ["Bestseller"],
    inStock: true,
  },
  {
    id: "bl-luxe-003",
    slug: "the-standard-glueless-bob",
    title: "The Standard",
    line: "luxe",
    avatar: "transformation",
    tagline: "Four minutes. No adhesive. No compromise.",
    description:
      "A glueless unit engineered for the woman whose morning does not have room for a wig. Pre-cut lace, adjustable band, silicone grip. It goes on in the time it takes coffee to brew and reads as an expensive salon blowout all day.",
    price: 58500,
    currency: "USD",
    texture: "straight",
    laceType: "glueless",
    shade: "natural-black",
    density: "150%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      {
        name: "Length",
        values: LENGTHS.slice(0, 4),
      },
      { name: "Shade", values: SHADES.slice(0, 4) },
    ],
    images: [
      { src: "velvet", alt: "The Standard glueless bob, natural black" },
      { src: "plum", alt: "Adjustable band and silicone grip detail" },
    ],
    specs: [
      { label: "Cap", value: "Glueless, pre-cut HD lace, adjustable band" },
      { label: "Install", value: "Under 4 minutes, no adhesive required" },
      { label: "Grip", value: "Medical-grade silicone, removable" },
      { label: "Hair", value: "Virgin Remy, cuticle aligned" },
      { label: "Lifespan", value: "12–18 months with Beyond Care maintenance" },
    ],
    rating: 4.9,
    reviewCount: 631,
    badges: ["Low maintenance", "Bestseller"],
    inStock: true,
  },
  {
    id: "bl-silk-001",
    slug: "the-restoration-silk-top",
    title: "The Restoration",
    line: "silk",
    avatar: "medical",
    tagline: "Made for scalps that have been through something.",
    description:
      "A silk-top cap with no lace against the skin, no adhesive required, and a breathable base built for sensitive and post-treatment scalps. Designed with the understanding that this is not a fashion purchase. It should feel like nothing, and look like it grew there.",
    price: 94500,
    currency: "USD",
    texture: "straight",
    laceType: "silk-top",
    shade: "natural-black",
    density: "150%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS.slice(0, 5) },
      { name: "Shade", values: SHADES },
      {
        name: "Cap Size",
        values: [
          { label: 'Petite (21")', value: "petite" },
          { label: 'Average (22.5")', value: "average" },
          { label: 'Large (23.5")', value: "large" },
        ],
      },
    ],
    images: [
      { src: "plum", alt: "The Restoration silk-top unit" },
      { src: "velvet", alt: "Silk base detail showing the scalp-side finish" },
    ],
    specs: [
      { label: "Cap", value: "Silk top — hair emerges from beneath, no knots visible" },
      { label: "Skin contact", value: "No lace, no adhesive, no tape required" },
      { label: "Base", value: "Breathable, hypoallergenic, seam-flat interior" },
      { label: "Fit", value: "Three cap sizes, fully adjustable" },
      { label: "Discretion", value: "Unbranded outer packaging as standard" },
    ],
    rating: 5.0,
    reviewCount: 198,
    badges: ["Sensitive scalp", "Discreet delivery"],
    inStock: true,
  },
  {
    id: "bl-men-001",
    slug: "beyond-system-one",
    title: "System One",
    line: "luxe",
    avatar: "men",
    tagline: "Restoration, not replacement.",
    description:
      "A hair system built to the same tolerances as our women's units and finished to be undetectable at conversational distance. Matched to your existing density and growth pattern. Shipped in unmarked packaging. Nobody is told anything.",
    price: 82500,
    currency: "USD",
    texture: "straight",
    laceType: "hd-swiss-full",
    density: "120%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      {
        name: "Base",
        values: [
          { label: "Full lace — most natural", value: "lace" },
          { label: "Skin — most durable", value: "skin" },
          { label: "Hybrid — lace front, skin back", value: "hybrid", priceDelta: 5000 },
        ],
      },
      {
        name: "Density",
        values: [
          { label: "100% — Mature", value: "100" },
          { label: "120% — Standard", value: "120" },
          { label: "140% — Full", value: "140", priceDelta: 6000 },
        ],
      },
      { name: "Shade", values: SHADES.slice(0, 3) },
    ],
    images: [
      { src: "mono", alt: "System One hair system, front hairline detail" },
      { src: "mono-2", alt: "System One base construction" },
    ],
    specs: [
      { label: "Base", value: "Full lace, skin, or hybrid" },
      {
        label: "Hairline",
        value: "Irregular, graduated — engineered against the straight-line tell",
      },
      { label: "Attachment", value: "Tape, adhesive, or clip — your choice" },
      { label: "Packaging", value: "Unmarked outer carton, no branding, plain invoice" },
      { label: "Consultation", value: "Private 1:1 fitting call included" },
    ],
    rating: 4.8,
    reviewCount: 143,
    badges: ["Discreet delivery", "Includes fitting call"],
    inStock: true,
  },
  {
    id: "bl-tryon-001",
    slug: "lace-test-kit",
    title: "The Lace Test",
    line: "try-on",
    avatar: "transformation",
    tagline: "Five dollars, so the eight hundred is never a gamble.",
    description:
      "Six lace swatches and five shade cards, sent to your door. Hold them against your skin in your own light — not a showroom's, not a ringlight's. Redeemable in full against any unit. We would rather spend five dollars than have you return eight hundred.",
    price: 500,
    currency: "USD",
    options: [],
    images: [{ src: "blush", alt: "The Lace Test kit — lace swatches and shade cards" }],
    specs: [
      { label: "Contents", value: "6 HD Swiss lace swatches, 5 shade cards" },
      { label: "Redeemable", value: "Full $5 credited against any unit purchase" },
      { label: "Shipping", value: "Free, worldwide" },
      {
        label: "Why",
        value: "Shade mismatch is the single largest cause of returns in this category",
      },
    ],
    rating: 4.9,
    reviewCount: 1840,
    badges: ["Fully redeemable", "Free shipping"],
    inStock: true,
  },
  {
    id: "bl-care-001",
    slug: "beyond-care-ritual-box",
    title: "The Care Ritual",
    line: "care",
    avatar: "transformation",
    tagline: "A unit lasts as long as the hands that keep it.",
    description:
      "Sulfate-free cleanser, lace-safe conditioner, adhesive solvent, and a gold-finished carbon comb — delivered monthly. Human hair does not renew itself. Everything it will ever be, it already is. This is how you keep it.",
    price: 6800,
    currency: "USD",
    subscribable: true,
    options: [
      {
        name: "Cadence",
        values: [
          { label: "Monthly — save 20%", value: "monthly" },
          { label: "Every 2 months — save 15%", value: "bimonthly" },
          { label: "One-time", value: "once", priceDelta: 1700 },
        ],
      },
    ],
    images: [{ src: "gold", alt: "The Care Ritual monthly maintenance box" }],
    specs: [
      { label: "Contents", value: "Cleanser 250ml, conditioner 250ml, solvent 100ml, carbon comb" },
      { label: "Formulation", value: "Sulfate-free, lace-safe, colour-safe" },
      { label: "Cadence", value: "Monthly, bi-monthly, or one-time" },
      { label: "Flexibility", value: "Pause, skip, or cancel from your account, anytime" },
    ],
    rating: 4.7,
    reviewCount: 924,
    badges: ["Subscription", "Save 20%"],
    inStock: true,
  },
  {
    id: "bl-luxe-004",
    slug: "the-capsule-deep-wave",
    title: "The Capsule — Deep Wave",
    line: "luxe",
    avatar: "editorial",
    tagline: "Made in a run of two hundred. Then never again.",
    description:
      "Our manufacturing floor holds twenty percent of its capacity in reserve for exactly this. A silhouette moves on Tuesday; the sample is cut by Friday. Two hundred units, numbered, and the mould is broken.",
    price: 64500,
    currency: "USD",
    texture: "deep-wave",
    laceType: "hd-swiss-13x4",
    shade: "brunette",
    density: "200%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS.slice(2, 7) },
      { name: "Shade", values: SHADES.slice(1, 5) },
    ],
    images: [
      { src: "aurora", alt: "The Capsule deep wave unit, brunette" },
      { src: "plum", alt: "Deep wave pattern detail" },
    ],
    specs: [
      { label: "Edition", value: "200 numbered units" },
      { label: "Cap", value: "13x4 HD Swiss frontal" },
      { label: "Pattern", value: "Deep wave, steam-set, reverts after washing" },
      { label: "Restock", value: "None. Capsule runs are not repeated." },
    ],
    rating: 4.8,
    reviewCount: 96,
    badges: ["Limited — 200 units", "New"],
    inStock: true,
  },
  {
    id: "bl-luxe-005",
    slug: "the-quiet-kinky-straight",
    title: "The Quiet",
    line: "luxe",
    avatar: "transformation",
    tagline: "Texture that reads as your own, because it was matched to it.",
    description:
      "Kinky-straight, cut to blend at the leave-out rather than sit on top of it. For anyone who has spent years choosing between a wig that matches their texture and a wig that matches their standards.",
    price: 71500,
    currency: "USD",
    texture: "kinky-straight",
    laceType: "hd-swiss-13x6",
    shade: "natural-black",
    density: "180%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS.slice(0, 6) },
      { name: "Shade", values: SHADES.slice(0, 3) },
      { name: "Density", values: DENSITIES },
    ],
    images: [
      { src: "velvet", alt: "The Quiet kinky-straight unit" },
      { src: "plum", alt: "Leave-out blend detail" },
    ],
    specs: [
      { label: "Cap", value: "13x6 HD Swiss frontal" },
      { label: "Texture", value: "Kinky-straight, blends at the leave-out" },
      { label: "Knots", value: "Individually bleached" },
      { label: "Lifespan", value: "18–30 months with Beyond Care maintenance" },
    ],
    rating: 4.9,
    reviewCount: 355,
    badges: ["Texture match"],
    inStock: true,
  },
  {
    id: "bl-care-002",
    slug: "the-hold-lace-adhesive",
    title: "The Hold",
    line: "care",
    avatar: "transformation",
    tagline: "Invisible for sixteen hours. Gone in ninety seconds.",
    description:
      "A waterproof lace adhesive that does not shine, does not flake at the hairline, and releases cleanly with our solvent instead of taking your edges with it.",
    price: 3400,
    currency: "USD",
    options: [
      {
        name: "Size",
        values: [
          { label: "38ml", value: "38" },
          { label: "80ml", value: "80", priceDelta: 2200 },
        ],
      },
    ],
    images: [{ src: "gold", alt: "The Hold lace adhesive" }],
    specs: [
      { label: "Hold", value: "Up to 16 hours, waterproof, sweat-resistant" },
      { label: "Finish", value: "Matte — no shine at the hairline" },
      { label: "Removal", value: "Clean release with Beyond Care solvent, ~90 seconds" },
      { label: "Skin", value: "Latex-free, dermatologically tested" },
    ],
    rating: 4.6,
    reviewCount: 1203,
    badges: ["Bestseller"],
    inStock: true,
  },
  {
    id: "bl-luxe-007",
    slug: "the-crown-coily-4a",
    title: "The Crown",
    line: "luxe",
    avatar: "transformation",
    tagline: "Coily, matched to the crown you already have.",
    description:
      "A 4A coil pattern that blends at the leave-out instead of arguing with it. Most brands treat textured units as an afterthought line. This one gets the same hand-tied cap, the same bleached knots, and the same batch guarantee as everything else on this site — because it is not an afterthought.",
    price: 69500,
    currency: "USD",
    texture: "curly",
    laceType: "hd-swiss-13x6",
    shade: "natural-black",
    density: "180%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS.slice(0, 5) },
      { name: "Shade", values: SHADES.slice(0, 3) },
      { name: "Density", values: DENSITIES },
    ],
    images: [
      { src: "aurora", alt: "The Crown coily 4A unit, natural black" },
      { src: "velvet", alt: "4A coil pattern and leave-out blend detail" },
    ],
    specs: [
      { label: "Cap", value: "13x6 HD Swiss frontal, hand-tied parting" },
      { label: "Pattern", value: "4A coil, steam-set, reverts true after wash day" },
      { label: "Blend", value: "Texture-matched at the leave-out" },
      { label: "Lifespan", value: "18–30 months with Beyond Care maintenance" },
    ],
    rating: 4.9,
    reviewCount: 218,
    badges: ["Texture match", "New"],
    inStock: true,
  },
  {
    id: "bl-luxe-008",
    slug: "the-ease-natural-density",
    title: "The Ease",
    line: "luxe",
    avatar: "transformation",
    tagline: "The density your own head would have chosen.",
    description:
      "A featherweight 130% unit built for people who want hair, not a headline. No wall of density, no obvious wig-line fullness — just soft, believable coverage for anyone stepping into themselves. Glueless, breathable, and gentle enough for daily wear.",
    price: 54500,
    currency: "USD",
    texture: "straight",
    laceType: "glueless",
    shade: "natural-black",
    density: "130%",
    origin: "Virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS.slice(0, 4) },
      { name: "Shade", values: SHADES.slice(0, 4) },
    ],
    images: [
      { src: "mono-2", alt: "The Ease natural-density glueless unit" },
      { src: "plum", alt: "Featherweight cap and natural density detail" },
    ],
    specs: [
      { label: "Cap", value: "Glueless, pre-cut HD lace, adjustable band" },
      { label: "Density", value: "130% — deliberately natural, never wall-of-hair" },
      { label: "Weight", value: "Under 160g at 16 inches" },
      { label: "Packaging", value: "Unbranded outer carton available at checkout" },
    ],
    rating: 4.8,
    reviewCount: 167,
    badges: ["Featherweight", "Everyday"],
    inStock: true,
  },
  {
    id: "bl-luxe-009",
    slug: "the-foundation-closure-set",
    title: "The Foundation",
    line: "luxe",
    avatar: "transformation",
    tagline: "A closure and three bundles. The stylist's raw material.",
    description:
      "A 13x4 HD closure with three batch-matched bundles — the set stylists and salons build custom units from. Every piece in the box is cut from the same production run, so the closure and the bundles agree on tone and texture without a colourist's intervention.",
    price: 39500,
    currency: "USD",
    texture: "body-wave",
    laceType: "hd-swiss-13x4",
    shade: "natural-black",
    origin: "Virgin Remy, cuticle intact, single production run per set",
    options: [
      {
        name: "Bundle Length",
        values: [
          { label: '14" / 16" / 18"', value: "14-16-18" },
          { label: '18" / 20" / 22"', value: "18-20-22", priceDelta: 12000 },
          { label: '22" / 24" / 26"', value: "22-24-26", priceDelta: 26000 },
        ],
      },
      { name: "Shade", values: SHADES.slice(0, 3) },
    ],
    images: [
      { src: "gold", alt: "The Foundation closure and bundle set" },
      { src: "plum", alt: "Batch-matched bundles detail" },
    ],
    specs: [
      { label: "Contents", value: "13x4 HD Swiss closure + 3 bundles, 100g each" },
      { label: "Batch rule", value: "All four pieces cut from one production run" },
      { label: "For", value: "Stylists, salons, and custom-unit builds" },
      { label: "Wholesale", value: "Salon tier pricing available — see the programme" },
    ],
    rating: 4.8,
    reviewCount: 289,
    badges: ["Stylist favourite"],
    inStock: true,
  },
  {
    id: "bl-pro-001",
    slug: "beyond-lace-pro-salon-program",
    title: "Beyond Lace Pro",
    line: "pro",
    avatar: "wholesale",
    tagline: "Your salon's name on our manufacturing floor.",
    description:
      "The private-label line. Your branding, our cap construction and batch consistency guarantee. Fifty-unit minimum, custom packaging, and a turnkey asset kit so you can sell it the day it lands.",
    price: 0,
    currency: "USD",
    options: [],
    images: [{ src: "plum", alt: "Beyond Lace Pro private label programme" }],
    specs: [
      { label: "MOQ", value: "50 units" },
      { label: "Tiers", value: "Bronze, Silver, Gold — volume-based" },
      { label: "Customisation", value: "Branded packaging, combs, hang tags, inserts" },
      { label: "Assets", value: "Lifestyle photography, spec sheets, launch copy" },
      { label: "Protection", value: "MAP enforced — your margin is contractually defended" },
    ],
    rating: 5.0,
    reviewCount: 41,
    badges: ["B2B", "Application required"],
    inStock: true,
  },
  {
    id: "bl-luxe-006",
    slug: "the-arrival-platinum",
    title: "The Arrival",
    line: "luxe",
    avatar: "editorial",
    tagline: "Platinum, lifted properly, with the cuticle still intact.",
    description:
      "Most platinum units are stripped until the hair gives up. Ours is lifted in stages across nine days by colourists who work on human heads. It moves like hair because it is still, structurally, hair.",
    price: 118000,
    currency: "USD",
    texture: "straight",
    laceType: "hd-swiss-full",
    shade: "platinum",
    density: "150%",
    origin: "Single-donor virgin Remy, cuticle intact",
    options: [
      { name: "Length", values: LENGTHS.slice(1, 6) },
      { name: "Density", values: DENSITIES.slice(0, 2) },
    ],
    images: [
      { src: "blush", alt: "The Arrival platinum full lace unit" },
      { src: "aurora", alt: "Platinum tone and cuticle integrity detail" },
    ],
    specs: [
      { label: "Cap", value: "Full HD Swiss lace, hand-tied throughout" },
      { label: "Lift", value: "Staged over nine days, cuticle preserved" },
      { label: "Tone", value: "Cool platinum, toner refresh recommended at 8 weeks" },
      { label: "Care", value: "Purple-toning cleanser included" },
    ],
    rating: 4.7,
    reviewCount: 74,
    badges: ["Colour specialist", "Signature"],
    inStock: false,
  },
];
